name: build-test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  make-build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y install libgtk-3-dev
      - name: Build project
        run: make artpad
      - uses: actions/checkout@master
        with:
          submodules: true
